
server {
    listen 80;

    location / {
        proxy_pass http://frontend:4200;
    }

    location /api/php/ {
        proxy_pass http://php-api/;
    }

    location /api/python/ {
        proxy_pass http://python-api:8000/;
    }

    location /pgadmin/ {
        proxy_pass http://pgadmin/;
    }
}
